(function(){
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);const date=v=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
  const login=document.querySelector('#adminLogin'),shell=document.querySelector('#adminShell'),toastEl=document.querySelector('#toast');let products=[],orders=[],expenses=[],categories=[];
  function toast(text){toastEl.textContent=text;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2500)}
  function showAuthenticatedState(authenticated){login.hidden=authenticated;shell.hidden=!authenticated;if(authenticated&&!document.querySelector('#cashClosingView').hidden)window.AdminCashClosing?.open()}
  if(StoreAPI.mode==='local'){document.querySelector('#emailLabel').hidden=true;document.querySelector('#loginHint').textContent='Modo local de demonstração. Use o PIN definido em js/config.js.'}else{document.querySelector('#modeTitle').textContent='Banco conectado';document.querySelector('#modeText').textContent='Sincronização ativa'}
  document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{if(!await StoreAPI.login(f.get('email'),f.get('password')))throw new Error('PIN incorreto.');showAuthenticatedState(true);e.target.reset();await loadAll()}catch(err){toast(err.message||'Não foi possível entrar.')}});
  document.querySelector('#logoutButton').addEventListener('click',async()=>{await StoreAPI.logout();showAuthenticatedState(false)});
  const viewTitles={orders:'Pedidos',products:'Produtos',confirmed:'Confirmados',cancelled:'Cancelados',dashboard:'Painel',expenses:'Saída',cashClosing:'Fechamento de caixa',control:'Controle geral'};
  document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b===btn));const view=btn.dataset.view;document.querySelectorAll('.admin-view').forEach(section=>section.hidden=section.id!==`${view}View`);document.querySelector('#viewTitle').textContent=viewTitles[view];if(view==='dashboard')renderDashboard();if(view==='control')window.AdminControl?.render({products,orders,expenses});if(view==='cashClosing')window.AdminCashClosing?.open();document.querySelector('.admin-sidebar').classList.remove('open')}));
  document.querySelector('#mobileMenu').addEventListener('click',()=>document.querySelector('.admin-sidebar').classList.toggle('open'));
  async function loadAll(){[products,orders,expenses,categories]=await Promise.all([StoreAPI.getProducts(true),StoreAPI.getOrders(),StoreAPI.getExpenses(),StoreAPI.getCategories()]);categories=[...new Set([...categories,...products.map(product=>product.category).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'pt-BR'));renderCategories();renderProducts();renderOrders();renderExpenses();renderDashboard();window.AdminControl?.render({products,orders,expenses});markLastRefresh()}
  function orderButtons(status){
    if(status==='pending')return '<button class="mini-button confirm" data-status="confirmed">Confirmar</button><button class="mini-button cancel" data-status="cancelled">Cancelar</button>';
    if(status==='confirmed')return '<button class="mini-button pending" data-status="pending">Voltar para pendente</button><button class="mini-button cancel" data-status="cancelled">Cancelar</button>';
    return '<button class="mini-button pending" data-status="pending">Voltar para pendente</button><button class="mini-button confirm" data-status="confirmed">Confirmar</button>';
  }
  function orderCard(o){const mismatch=Math.abs(Number(o.clientTotal)-Number(o.trustedTotal))>.009;return `<article class="order-row" data-id="${o.id}"><div class="order-summary"><div><span class="order-code">#${o.code}</span><h3>${o.customerName}</h3><small>${date(o.createdAt)}</small></div><div><span class="status ${o.status}">${o.status==='pending'?'Aguardando':o.status==='confirmed'?'Confirmado':'Cancelado'}</span><div class="verification ${mismatch?'alert':'ok'}">${mismatch?'⚠ Total divergente':'✓ Total calculado no servidor'}</div></div><div><small>Total</small><strong>${money(o.trustedTotal)}</strong></div><div class="order-actions order-summary-actions">${orderButtons(o.status)}<button class="mini-button" data-expand>Detalhes</button></div></div><div class="order-details"><p><strong>${o.deliveryType}:</strong> ${o.address||'Retirada no local'}<br><strong>Pagamento:</strong> ${o.payment}${o.notes?`<br><strong>Observação:</strong> ${o.notes}`:''}</p><ul>${(o.items||[]).map(i=>`<li>${i.quantity}x ${i.name} — ${money(i.subtotal)}</li>`).join('')}</ul><p>Valor informado pelo navegador: <strong>${money(o.clientTotal)}</strong><br>Valor conferido pelos produtos: <strong>${money(o.trustedTotal)}</strong></p></div></article>`}
  function renderOrderList(selector,list,emptyText){document.querySelector(selector).innerHTML=list.length?list.map(orderCard).join(''):`<div class="empty-state">${emptyText}</div>`}
  function renderOrders(){
    const pending=orders.filter(o=>o.status==='pending'),confirmed=orders.filter(o=>o.status==='confirmed'),cancelled=orders.filter(o=>o.status==='cancelled');
    document.querySelector('#pendingBadge').textContent=pending.length;
    document.querySelector('#confirmedBadge').textContent=confirmed.length;
    document.querySelector('#cancelledBadge').textContent=cancelled.length;
    document.querySelector('#statPending').textContent=pending.length;
    document.querySelector('#statConfirmed').textContent=confirmed.length;
    document.querySelector('#statRevenue').textContent=money(confirmed.reduce((sum,o)=>sum+Number(o.trustedTotal),0));
    document.querySelector('#statPendingValue').textContent=money(pending.reduce((sum,o)=>sum+Number(o.trustedTotal),0));
    renderOrderList('#ordersList',pending,'Nenhum pedido aguardando confirmação.');
    renderOrderList('#confirmedOrdersList',confirmed,'Nenhum pedido confirmado.');
    renderOrderList('#cancelledOrdersList',cancelled,'Nenhum pedido cancelado.');
  }
  document.querySelectorAll('.orders-list').forEach(list=>list.addEventListener('click',async e=>{const row=e.target.closest('.order-row');if(!row)return;if(e.target.dataset.expand!==undefined){row.classList.toggle('expanded');return}const status=e.target.dataset.status;if(status){const currentOrder=orders.find(order=>order.id===row.dataset.id);if(currentOrder?.status==='confirmed'&&!confirm('Tem certeza que deseja alterar o item confirmado?'))return;if(currentOrder?.status==='cancelled'&&!confirm('Tem certeza que deseja alterar o item cancelado?'))return;try{await StoreAPI.updateOrderStatus(row.dataset.id,status);orders=orders.map(order=>order.id===row.dataset.id?{...order,status}:order);renderOrders();renderDashboard();toast('Status atualizado');orders=await StoreAPI.getOrders();renderOrders();renderDashboard();markLastRefresh()}catch(err){toast(err.message||'Não foi possível atualizar o pedido.')}}}));
  let refreshing=false;
  function markLastRefresh(){const element=document.querySelector('#lastRefresh');if(element)element.textContent=`Atualizado às ${new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())} · a cada 10s`}
  async function syncOrders(notify=false){if(refreshing||shell.hidden)return;const button=document.querySelector('#refreshOrders');refreshing=true;button.classList.add('loading');button.disabled=true;try{[orders,expenses]=await Promise.all([StoreAPI.getOrders(),StoreAPI.getExpenses()]);renderOrders();renderExpenses();renderDashboard();window.AdminControl?.render({products,orders,expenses});markLastRefresh();if(notify)toast('Dados atualizados')}catch(err){if(notify)toast(err.message||'Não foi possível atualizar os dados.')}finally{refreshing=false;button.classList.remove('loading');button.disabled=false}}
  document.querySelector('#refreshOrders').addEventListener('click',()=>syncOrders(true));
  setInterval(()=>syncOrders(false),10000);

  const manualDialog=document.querySelector('#manualOrderDialog'),manualForm=document.querySelector('#manualOrderForm'),manualItems=document.querySelector('#manualOrderItems');
  function productOptions(selected=''){return products.filter(product=>product.available).map(product=>`<option value="${product.id}" ${product.id===selected?'selected':''}>${product.name} — ${money(product.price)}</option>`).join('')}
  function addManualItem(selected=''){if(!products.some(product=>product.available)){toast('Cadastre um produto disponível antes de criar o pedido.');return}manualItems.insertAdjacentHTML('beforeend',`<div class="manual-item-row"><label>Produto<select data-manual-product required>${productOptions(selected)}</select></label><label>Quantidade<input data-manual-quantity type="number" min="1" max="100" value="1" required /></label><div class="manual-line-total"><small>Subtotal</small><strong>R$ 0,00</strong></div><button class="icon-button manual-remove" type="button" data-remove-manual aria-label="Remover produto">×</button></div>`);updateManualTotal()}
  function manualLines(){return [...manualItems.querySelectorAll('.manual-item-row')].map(row=>{const product=products.find(item=>item.id===row.querySelector('[data-manual-product]').value),quantity=Math.max(1,Number(row.querySelector('[data-manual-quantity]').value)||1);return product?{product,quantity,subtotal:Number(product.price)*quantity}:null}).filter(Boolean)}
  function updateManualTotal(){const lines=manualLines();[...manualItems.querySelectorAll('.manual-item-row')].forEach((row,index)=>{row.querySelector('.manual-line-total strong').textContent=money(lines[index]?.subtotal||0)});document.querySelector('#manualOrderTotal').textContent=money(lines.reduce((sum,line)=>sum+line.subtotal,0))}
  document.querySelector('#addManualOrder').addEventListener('click',()=>{if(!products.some(product=>product.available)){toast('Cadastre um produto disponível antes de criar o pedido.');return}manualForm.reset();manualItems.innerHTML='';addManualItem();manualDialog.showModal()});
  document.querySelector('#addManualItem').addEventListener('click',()=>addManualItem());
  manualForm.addEventListener('submit',e=>{if(e.submitter?.value!=='cancel')e.preventDefault()});
  manualItems.addEventListener('input',updateManualTotal);
  manualItems.addEventListener('change',updateManualTotal);
  manualItems.addEventListener('click',e=>{if(!e.target.closest('[data-remove-manual]'))return;e.target.closest('.manual-item-row').remove();if(!manualItems.children.length)addManualItem();updateManualTotal()});
  document.querySelector('#saveManualOrder').addEventListener('click',async()=>{if(!manualForm.reportValidity())return;const lines=manualLines();if(!lines.length){toast('Adicione pelo menos um produto.');return}const fields=new FormData(manualForm),button=document.querySelector('#saveManualOrder'),total=lines.reduce((sum,line)=>sum+line.subtotal,0);button.disabled=true;button.textContent='Salvando...';try{const order=await StoreAPI.createOrder({customerName:fields.get('customerName').trim(),deliveryType:'Retirada',address:'Venda presencial',payment:fields.get('payment'),notes:fields.get('notes').trim(),clientTotal:total,items:lines.map(line=>({productId:line.product.id,quantity:line.quantity}))});if(fields.get('status')==='confirmed')await StoreAPI.updateOrderStatus(order.id,'confirmed');orders=await StoreAPI.getOrders();renderOrders();renderDashboard();markLastRefresh();manualDialog.close();toast(`Pedido ${order.code} registrado`)}catch(err){toast(err.message||'Não foi possível salvar o pedido.')}finally{button.disabled=false;button.textContent='Salvar pedido'}});

  const expenseForm=document.querySelector('#expenseForm'),expensesList=document.querySelector('#expensesList');
  function setExpenseDate(){const input=expenseForm.elements.spentAt,now=new Date();input.value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)}
  const expenseDate=value=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value));
  function renderExpenses(){const total=expenses.reduce((sum,expense)=>sum+Number(expense.amount),0),largest=Math.max(0,...expenses.map(expense=>Number(expense.amount))),people=new Set(expenses.map(expense=>expense.spentBy?.trim().toLowerCase()).filter(Boolean));document.querySelector('#expenseTotal').textContent=money(total);document.querySelector('#expenseCount').textContent=expenses.length;document.querySelector('#expenseLargest').textContent=money(largest);document.querySelector('#expensePeople').textContent=people.size;expensesList.innerHTML=expenses.length?expenses.map(expense=>`<article class="expense-row" data-id="${expense.id}"><div class="expense-row-icon">↘</div><div class="expense-row-main"><span>${expense.description}</span><strong>${expense.spentBy}</strong><small>${expenseDate(expense.spentAt||expense.createdAt)}</small></div><b>− ${money(expense.amount)}</b><button class="mini-button cancel" type="button" data-delete-expense="${expense.id}">Excluir</button></article>`).join(''):'<div class="empty-state">Nenhuma saída registrada.</div>'}
  expenseForm.addEventListener('submit',async e=>{e.preventDefault();if(!expenseForm.reportValidity())return;const fields=new FormData(expenseForm),button=expenseForm.querySelector('button[type="submit"]');button.disabled=true;button.innerHTML='<span>−</span> Registrando...';try{await StoreAPI.createExpense({description:fields.get('description').trim(),amount:Number(fields.get('amount')),spentBy:fields.get('spentBy').trim(),spentAt:new Date(`${fields.get('spentAt')}T12:00:00`).toISOString()});expenses=await StoreAPI.getExpenses();renderExpenses();renderDashboard();expenseForm.reset();setExpenseDate();toast('Saída registrada')}catch(err){toast(err.message||'Não foi possível registrar a saída.')}finally{button.disabled=false;button.innerHTML='<span>−</span> Registrar saída'}});
  expensesList.addEventListener('click',async e=>{const button=e.target.closest('[data-delete-expense]');if(!button||!confirm('Tem certeza que deseja excluir esta saída?'))return;try{await StoreAPI.deleteExpense(button.dataset.deleteExpense);expenses=await StoreAPI.getExpenses();renderExpenses();renderDashboard();toast('Saída excluída')}catch(err){toast(err.message||'Não foi possível excluir a saída.')}});
  setExpenseDate();

  const localDayKey=value=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const dayLabel=key=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit'}).format(new Date(`${key}T00:00:00`));
  function dashboardSelection(){const period=document.querySelector('#dashboardPeriod').value;if(period==='all')return orders.slice();const start=new Date();start.setHours(0,0,0,0);if(period!=='today')start.setDate(start.getDate()-(Number(period)-1));return orders.filter(order=>new Date(order.createdAt)>=start)}
  function dashboardExpenseSelection(){const period=document.querySelector('#dashboardPeriod').value;if(period==='all')return expenses.slice();const start=new Date();start.setHours(0,0,0,0);if(period!=='today')start.setDate(start.getDate()-(Number(period)-1));return expenses.filter(expense=>new Date(expense.spentAt||expense.createdAt)>=start)}
  function dashboardDays(selected){const period=document.querySelector('#dashboardPeriod').value;if(period==='all'){const keys=[...new Set(selected.map(order=>localDayKey(order.createdAt)))].sort();return keys.length?keys:[localDayKey(new Date())]}const count=period==='today'?1:Number(period);const days=[];for(let offset=count-1;offset>=0;offset--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-offset);days.push(localDayKey(d))}return days}
  let chartMode='value';
  function renderCashflow(selected,selectedExpenses){const days=dashboardDays([...selected,...selectedExpenses.map(expense=>({createdAt:expense.spentAt||expense.createdAt}))]),daily=days.map(day=>{const incomeOrders=selected.filter(order=>order.status==='confirmed'&&localDayKey(order.createdAt)===day),outcomeEntries=selectedExpenses.filter(expense=>localDayKey(expense.spentAt||expense.createdAt)===day);return{day,income:incomeOrders.reduce((sum,order)=>sum+Number(order.trustedTotal),0),outcome:outcomeEntries.reduce((sum,expense)=>sum+Number(expense.amount),0),incomeCount:incomeOrders.length,outcomeCount:outcomeEntries.length}}),values=daily.flatMap(item=>chartMode==='value'?[item.income,item.outcome]:[item.incomeCount,item.outcomeCount]),maximum=Math.max(1,...values),axisValue=value=>chartMode==='value'?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1}).format(value):Math.round(value),barValue=(item,type)=>chartMode==='value'?item[type]:item[`${type}Count`],detailValue=(item,type)=>chartMode==='value'?money(item[type]):`${item[`${type}Count`]} ${item[`${type}Count`]===1?'registro':'registros'}`;document.querySelector('#cashflowChart').innerHTML=`<div class="chart-layout"><div class="chart-y-axis"><span>${axisValue(maximum)}</span><span>${axisValue(maximum/2)}</span><span>${axisValue(0)}</span></div><div class="chart-stage">${daily.map(item=>`<div class="chart-column"><div class="chart-bars"><span class="chart-bar-wrap"><i class="chart-bar income-bar" style="height:${barValue(item,'income')?Math.max(6,barValue(item,'income')/maximum*100)+'%':'2px'}"></i><em class="chart-tooltip"><b>Entradas</b>${detailValue(item,'income')}</em></span><span class="chart-bar-wrap"><i class="chart-bar outcome-bar" style="height:${barValue(item,'outcome')?Math.max(6,barValue(item,'outcome')/maximum*100)+'%':'2px'}"></i><em class="chart-tooltip"><b>Saídas</b>${detailValue(item,'outcome')}</em></span></div><small>${dayLabel(item.day)}</small></div>`).join('')}</div></div>`}
  function rankingMarkup(entries,emptyText){if(!entries.length)return `<div class="dashboard-empty">${emptyText}</div>`;const maximum=Math.max(...entries.map(entry=>entry.value),1);return entries.map((entry,index)=>`<div class="ranking-row"><div><span><b>${index+1}</b>${entry.label}</span><strong>${entry.display}</strong></div><div class="ranking-track"><i style="width:${Math.max(4,entry.value/maximum*100)}%"></i></div></div>`).join('')}
  function paymentMarkup(entries,total){if(!entries.length||total<=0)return '<div class="dashboard-empty">Nenhuma entrada confirmada no período.</div>';const colors=['#ffc400','#51d88a','#4d8dff','#b86cff','#ff8b4d'],segments=[];let cursor=0;entries.forEach((entry,index)=>{const start=cursor,end=cursor+(entry.value/total*100);segments.push(`${colors[index%colors.length]} ${start}% ${end}%`);cursor=end});return `<div class="payment-visual"><div class="payment-donut" style="background:conic-gradient(${segments.join(',')})"><div><strong>${money(total)}</strong><small>Total recebido</small></div></div><div class="payment-legend">${entries.map((entry,index)=>`<div><span><i style="background:${colors[index%colors.length]}"></i>${entry.label}</span><strong>${Math.round(entry.value/total*100)}%</strong></div>`).join('')}</div></div>`}
  function salesChannelMarkup(inPerson,online){const channel=data=>{const confirmed=data.filter(order=>order.status==='confirmed'),pending=data.filter(order=>order.status==='pending'),cancelled=data.filter(order=>order.status==='cancelled');return{total:data.length,confirmed:confirmed.length,pending:pending.length,cancelled:cancelled.length,revenue:confirmed.reduce((sum,order)=>sum+Number(order.trustedTotal),0)}};const store=channel(inPerson),web=channel(online),totalRevenue=store.revenue+web.revenue||1,box=(label,icon,data,type)=>`<article class="channel-box ${type}"><div class="channel-name"><i>${icon}</i><div><span>${label}</span><small>${data.total} ${data.total===1?'pedido':'pedidos'} no período</small></div></div><strong>${money(data.revenue)}</strong><div class="channel-progress"><i style="width:${data.revenue/totalRevenue*100}%"></i></div><div class="channel-statuses"><span class="confirmed">${data.confirmed} confirmados</span><span class="pending">${data.pending} pendentes</span><span class="cancelled">${data.cancelled} cancelados</span></div></article>`;return `<div class="channel-comparison">${box('Venda presencial','⌂',store,'store')}${box('Pedidos online','⌁',web,'online')}</div>`}
  function renderDashboard(){if(!document.querySelector('#dashboardView'))return;const selected=dashboardSelection(),selectedExpenses=dashboardExpenseSelection(),confirmed=selected.filter(order=>order.status==='confirmed'),cancelled=selected.filter(order=>order.status==='cancelled'),pending=selected.filter(order=>order.status==='pending'),inPerson=selected.filter(order=>order.address==='Venda presencial'),online=selected.filter(order=>order.address!=='Venda presencial'),inPersonConfirmed=inPerson.filter(order=>order.status==='confirmed'),inPersonPending=inPerson.filter(order=>order.status==='pending'),inPersonCancelled=inPerson.filter(order=>order.status==='cancelled'),inPersonRevenue=inPersonConfirmed.reduce((sum,order)=>sum+Number(order.trustedTotal),0),income=confirmed.reduce((sum,order)=>sum+Number(order.trustedTotal),0),outcome=selectedExpenses.reduce((sum,expense)=>sum+Number(expense.amount),0),pendingValue=pending.reduce((sum,order)=>sum+Number(order.trustedTotal),0),decided=confirmed.length+cancelled.length;
    document.querySelector('#dashIncome').textContent=money(income);document.querySelector('#dashIncomeCount').textContent=`${confirmed.length} ${confirmed.length===1?'pedido':'pedidos'}`;
    document.querySelector('#dashOutcome').textContent=money(outcome);document.querySelector('#dashOutcomeCount').textContent=`${selectedExpenses.length} ${selectedExpenses.length===1?'lançamento':'lançamentos'}`;
    document.querySelector('#dashBalance').textContent=money(income-outcome);document.querySelector('#dashPending').textContent=money(pendingValue);document.querySelector('#dashPendingCount').textContent=`${pending.length} aguardando`;
    document.querySelector('#dashAverage').textContent=money(confirmed.length?income/confirmed.length:0);document.querySelector('#dashConversion').textContent=`${decided?Math.round(confirmed.length/decided*100):0}%`;
    document.querySelector('#dashInPersonRevenue').textContent=money(inPersonRevenue);document.querySelector('#dashInPersonRevenueCount').textContent=`${inPersonConfirmed.length} confirmados`;
    document.querySelector('#dashInPersonOrders').textContent=inPerson.length;document.querySelector('#dashInPersonStatus').textContent=`${inPersonPending.length} pendentes · ${inPersonCancelled.length} cancelados`;
    renderCashflow(selected,selectedExpenses);
    const payments=Object.entries(confirmed.reduce((result,order)=>{const key=order.payment||'Não informado';result[key]=(result[key]||0)+Number(order.trustedTotal);return result},{})).map(([label,value])=>({label,value,display:money(value)})).sort((a,b)=>b.value-a.value);
    document.querySelector('#paymentBreakdown').innerHTML=paymentMarkup(payments,income);
    const productTotals={};confirmed.forEach(order=>(order.items||[]).forEach(item=>{const key=item.productId||item.name;if(!productTotals[key])productTotals[key]={label:item.name,value:0,total:0};productTotals[key].value+=Number(item.quantity);productTotals[key].total+=Number(item.subtotal)}));const top=Object.values(productTotals).sort((a,b)=>b.value-a.value).slice(0,6).map(item=>({...item,display:`${item.value} un. · ${money(item.total)}`}));
    document.querySelector('#topProducts').innerHTML=rankingMarkup(top,'Nenhum produto confirmado no período.');
    const movements=[...confirmed.map(order=>({type:'confirmed',time:order.createdAt,title:`#${order.code} · ${order.customerName}`,detail:order.payment,amount:Number(order.trustedTotal)})),...selectedExpenses.map(expense=>({type:'expense',time:expense.spentAt||expense.createdAt,title:expense.description,detail:expense.spentBy,amount:Number(expense.amount)}))].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,8);document.querySelector('#recentMovements').innerHTML=movements.length?movements.map(item=>`<div class="movement-row ${item.type}"><div><span>${item.type==='confirmed'?'Entrada confirmada':'Saída registrada'}</span><strong>${item.title}</strong><small>${date(item.time)} · ${item.detail}</small></div><b>${item.type==='confirmed'?'+':'−'} ${money(item.amount)}</b></div>`).join(''):'<div class="dashboard-empty">Nenhuma movimentação no período.</div>';
    document.querySelector('#salesChannels').innerHTML=salesChannelMarkup(inPerson,online);
  }
  document.querySelector('#dashboardPeriod').addEventListener('change',renderDashboard);
  document.querySelectorAll('[data-chart-mode]').forEach(button=>button.addEventListener('click',()=>{chartMode=button.dataset.chartMode;document.querySelectorAll('[data-chart-mode]').forEach(item=>item.classList.toggle('active',item===button));renderCashflow(dashboardSelection(),dashboardExpenseSelection())}));
  const productCategoryFilter=document.querySelector('#productCategoryFilter'),productCategorySelect=document.querySelector('#productCategorySelect'),categoryDialog=document.querySelector('#categoryDialog'),categoryList=document.querySelector('#categoryList'),newCategoryName=document.querySelector('#newCategoryName');
  const escapeHtml=value=>String(value??'').replace(/[&<>"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[character]));
  function renderCategories(preferred=''){const currentFilter=productCategoryFilter.value||'all',currentProductCategory=preferred||productCategorySelect.value;productCategoryFilter.innerHTML='<option value="all">Todas as categorias</option>'+categories.map(category=>`<option value="${escapeHtml(category)}">${escapeHtml(category)}</option>`).join('');productCategoryFilter.value=categories.includes(currentFilter)?currentFilter:'all';productCategorySelect.innerHTML=categories.map(category=>`<option value="${escapeHtml(category)}">${escapeHtml(category)}</option>`).join('');if(categories.includes(currentProductCategory))productCategorySelect.value=currentProductCategory;categoryList.innerHTML=categories.length?categories.map(category=>`<div class="category-row"><span>${escapeHtml(category)}</span><small>${products.filter(product=>product.category===category).length} produtos</small><button class="mini-button cancel" type="button" data-delete-category="${encodeURIComponent(category)}">Remover</button></div>`).join(''):'<div class="empty-state">Nenhuma categoria cadastrada.</div>'}
  function renderProducts(){const category=productCategoryFilter.value||'all',filtered=products.filter(product=>category==='all'||product.category===category),container=document.querySelector('#adminProducts');container.innerHTML=filtered.length?filtered.map(p=>`<div class="admin-product-row"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><small>${p.category}</small></div><strong>${money(p.price)}</strong><span class="availability ${p.available?'':'off'}">${p.available?'Em estoque':'Em falta'}</span><div class="product-row-actions"><button class="mini-button stock-button ${p.available?'':'reactivate'}" data-stock="${p.id}">${p.available?'Marcar em falta':'Reativar'}</button><button class="mini-button" data-edit="${p.id}">Editar</button><button class="mini-button cancel" data-delete="${p.id}">Excluir</button></div></div>`).join(''):'<div class="empty-state">Nenhum produto nesta categoria.</div>'}
  productCategoryFilter.addEventListener('change',renderProducts);
  document.querySelector('#manageCategories').addEventListener('click',()=>{renderCategories();newCategoryName.value='';categoryDialog.showModal()});
  document.querySelector('#saveCategory').addEventListener('click',async()=>{const name=newCategoryName.value.trim();if(name.length<2){toast('Informe uma categoria com pelo menos 2 caracteres.');return}if(categories.some(category=>category.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){toast('Esta categoria já existe.');return}try{await StoreAPI.createCategory(name);categories=await StoreAPI.getCategories();categories=[...new Set([...categories,...products.map(product=>product.category).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'pt-BR'));renderCategories(name);newCategoryName.value='';toast('Categoria adicionada')}catch(err){toast(err.message||'Não foi possível adicionar a categoria.')}});
  categoryList.addEventListener('click',async e=>{const button=e.target.closest('[data-delete-category]');if(!button)return;const name=decodeURIComponent(button.dataset.deleteCategory);if(products.some(product=>product.category===name)){toast('Altere a categoria dos produtos antes de removê-la.');return}if(!confirm(`Tem certeza que deseja remover a categoria “${name}”?`))return;try{await StoreAPI.deleteCategory(name);categories=await StoreAPI.getCategories();renderCategories();renderProducts();toast('Categoria removida')}catch(err){toast(err.message||'Não foi possível remover a categoria.')}});
  const dialog=document.querySelector('#productDialog'),form=document.querySelector('#productForm'),productImageFile=document.querySelector('#productImageFile'),productImagePreview=document.querySelector('#productImagePreviewImg'),productImageEmpty=document.querySelector('#productImageEmpty'),productImageStatus=document.querySelector('#productImageStatus');
  function showProductImage(src){productImagePreview.hidden=!src;productImageEmpty.hidden=Boolean(src);if(src)productImagePreview.src=src;else productImagePreview.removeAttribute('src')}
  function validateProductImage(file){if(!file)return true;const allowed=['image/jpeg','image/png','image/webp','image/avif'];if(!allowed.includes(file.type)){toast('Escolha uma imagem JPG, PNG, WEBP ou AVIF.');return false}if(file.size>5*1024*1024){toast('A imagem deve ter no máximo 5 MB.');return false}return true}
  productImagePreview.addEventListener('error',()=>{productImagePreview.hidden=true;productImageEmpty.hidden=false;productImageEmpty.textContent='Prévia indisponível'});
  productImageFile.addEventListener('change',()=>{const file=productImageFile.files[0];if(!file)return;if(!validateProductImage(file)){productImageFile.value='';return}productImageStatus.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;const reader=new FileReader();reader.onload=()=>showProductImage(reader.result);reader.readAsDataURL(file)});
  form.elements.image.addEventListener('change',()=>{if(!productImageFile.files.length)showProductImage(form.elements.image.value.trim())});
  function openProduct(p={id:'',name:'',description:'',price:'',category:'',image:'',available:true}){Object.keys(p).forEach(k=>{if(form.elements[k]){if(form.elements[k].type==='checkbox')form.elements[k].checked=p[k];else form.elements[k].value=p[k]??''}});productImageFile.value='';productImageStatus.textContent='Nenhum arquivo selecionado';productImageEmpty.textContent='Imagem';showProductImage(p.image||'');document.querySelector('#dialogTitle').textContent=p.id?'Editar produto':'Novo produto';dialog.showModal()}
  document.querySelector('#addProduct').addEventListener('click',()=>{if(!categories.length){toast('Adicione uma categoria antes de cadastrar o produto.');categoryDialog.showModal();return}openProduct()});document.querySelector('#adminProducts').addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete,stock=e.target.dataset.stock;if(edit)openProduct(products.find(p=>p.id===edit));if(stock){const current=products.find(product=>product.id===stock);if(!current)return;const updated={id:current.id,name:current.name,description:current.description,price:Number(current.price),category:current.category,image:current.image,available:!current.available};try{await StoreAPI.saveProduct(updated);products=products.map(product=>product.id===stock?updated:product);renderProducts();toast(updated.available?'Produto reativado no catálogo':'Produto marcado como em falta')}catch(err){toast(err.message||'Não foi possível alterar o estoque.')}}if(del&&confirm('Excluir este produto do catálogo?')){await StoreAPI.deleteProduct(del);products=await StoreAPI.getProducts(true);renderProducts();renderCategories();toast('Produto excluído')}});
  document.querySelector('#saveProduct').addEventListener('click',async()=>{if(!form.reportValidity())return;const f=new FormData(form),file=productImageFile.files[0],button=document.querySelector('#saveProduct');if(file&&!validateProductImage(file))return;let image=f.get('image').trim();if(!file&&!image){toast('Selecione uma imagem ou informe um caminho.');return}button.disabled=true;button.textContent=file?'Enviando imagem...':'Salvando...';try{if(file){image=await StoreAPI.uploadProductImage(file);productImageStatus.textContent='Upload concluído'}const product={id:f.get('id')||crypto.randomUUID(),name:f.get('name').trim(),description:f.get('description').trim(),price:Number(f.get('price')),category:f.get('category').trim(),image,available:form.available.checked};await StoreAPI.saveProduct(product);products=await StoreAPI.getProducts(true);renderProducts();renderCategories(product.category);dialog.close();toast('Produto salvo')}catch(err){toast(err.message||'Não foi possível salvar o produto.')}finally{button.disabled=false;button.textContent='Salvar'}});
  window.addEventListener('snoop:data-reset',()=>loadAll().catch(err=>toast(err.message||'Não foi possível atualizar os dados após o reset.')));
  (async()=>{try{const authenticated=await StoreAPI.isAuthenticated();showAuthenticatedState(authenticated);if(authenticated)await loadAll()}catch(err){showAuthenticatedState(false);toast(err.message||'Não foi possível verificar a sessão.')}})();
})();
