(function(){
  const money=(v)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
  const els={grid:document.querySelector('#productGrid'),categories:document.querySelector('#categories'),search:document.querySelector('#searchInput'),drawer:document.querySelector('#cartDrawer'),overlay:document.querySelector('#overlay'),items:document.querySelector('#cartItems'),empty:document.querySelector('#cartEmpty'),form:document.querySelector('#checkoutForm'),count:document.querySelector('#cartCount'),total:document.querySelector('#cartTotal'),toast:document.querySelector('#toast')};
  let products=[];let cart=JSON.parse(localStorage.getItem('snoop_cart_v1')||'{}');let active='Todos';
  function toast(text){els.toast.textContent=text;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2400)}
  function persist(){localStorage.setItem('snoop_cart_v1',JSON.stringify(cart));renderCart()}
  function renderCategories(){const cats=['Todos',...new Set(products.map(p=>p.category))];els.categories.innerHTML=cats.map(c=>`<button class="category-button ${c===active?'active':''}" data-category="${c}">${c}</button>`).join('')}
  function renderProducts(){const term=els.search.value.trim().toLowerCase();const filtered=products.filter(p=>(active==='Todos'||p.category===active)&&(p.name+' '+p.description).toLowerCase().includes(term));els.grid.innerHTML=filtered.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-content"><span class="product-category">${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-buy"><strong class="product-price">${money(p.price)}</strong><button class="add-button" data-add="${p.id}">Adicionar</button></div></div></article>`).join('');document.querySelector('#emptyState').hidden=filtered.length>0}
  function cartLines(){return Object.entries(cart).map(([id,quantity])=>{const product=products.find(p=>p.id===id);return product?{...product,quantity}:null}).filter(Boolean)}
  function renderCart(){const lines=cartLines();const count=lines.reduce((s,i)=>s+i.quantity,0);const total=lines.reduce((s,i)=>s+i.price*i.quantity,0);els.count.textContent=count;els.total.textContent=money(total);els.empty.hidden=lines.length>0;els.form.hidden=!lines.length;els.items.innerHTML=lines.map(i=>`<div class="cart-line"><img src="${i.image}" alt=""><div><h4>${i.name}</h4><small>${money(i.price*i.quantity)}</small><div class="quantity"><button data-qty="${i.id}" data-delta="-1">−</button><b>${i.quantity}</b><button data-qty="${i.id}" data-delta="1">+</button></div></div><button class="remove-button" data-remove="${i.id}">Remover</button></div>`).join('')}
  function openCart(){els.overlay.hidden=false;els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeCart(){els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true');els.overlay.hidden=true;document.body.style.overflow=''}
  els.grid.addEventListener('click',e=>{const id=e.target.dataset.add;if(!id)return;cart[id]=(cart[id]||0)+1;persist();toast('Produto adicionado ao carrinho')});
  els.categories.addEventListener('click',e=>{if(!e.target.dataset.category)return;active=e.target.dataset.category;renderCategories();renderProducts()});els.search.addEventListener('input',renderProducts);
  els.items.addEventListener('click',e=>{const id=e.target.dataset.qty||e.target.dataset.remove;if(!id)return;if(e.target.dataset.remove)delete cart[id];else{cart[id]+=Number(e.target.dataset.delta);if(cart[id]<=0)delete cart[id]}persist()});
  document.querySelector('#openCart').addEventListener('click',openCart);document.querySelector('#closeCart').addEventListener('click',closeCart);els.overlay.addEventListener('click',closeCart);
  els.form.deliveryType.addEventListener('change',()=>{const delivery=els.form.deliveryType.value==='Entrega';document.querySelector('#addressField').hidden=!delivery;els.form.address.required=delivery});
  els.form.addEventListener('submit',async e=>{e.preventDefault();const lines=cartLines();if(!lines.length)return;const form=new FormData(els.form);const total=lines.reduce((s,i)=>s+i.price*i.quantity,0);const button=els.form.querySelector('button[type=submit]');button.disabled=true;button.querySelector('strong').textContent='Registrando...';try{const order=await StoreAPI.createOrder({customerName:form.get('customerName').trim(),deliveryType:form.get('deliveryType'),address:form.get('address').trim(),payment:form.get('payment'),notes:form.get('notes').trim(),clientTotal:total,items:lines.map(i=>({productId:i.id,quantity:i.quantity}))});const itemText=order.items.map(i=>`• ${i.quantity}x ${i.name} — ${money(i.subtotal)}`).join('\n');const msg=`Olá! Quero fazer este pedido:\n\n*Pedido ${order.code}*\n${itemText}\n\n*Total dos produtos: ${money(order.trustedTotal)}*\n\nCliente: ${order.customerName}\n${order.deliveryType}: ${order.address||'Retirada no local'}\nPagamento: ${order.payment}${order.notes?`\nObservação: ${order.notes}`:''}\n\nCódigo para conferência: ${order.code}`;window.open(`https://wa.me/${APP_CONFIG.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener');cart={};persist();els.form.reset();closeCart();toast(`Pedido ${order.code} registrado`) }catch(err){toast(err.message||'Não foi possível registrar o pedido.')}finally{button.disabled=false;button.querySelector('strong').textContent='Enviar pedido'}});
  (async()=>{try{products=await StoreAPI.getProducts();renderCategories();renderProducts();renderCart();els.form.address.required=true}catch(err){toast('Erro ao carregar o catálogo.')}})();
})();
